### ISSUE TITLE
Subcategory definition of hate speech

### ISSUE THREAD

**Issue by ogencoglu** [xiaoleihuang/Multilingual_Fairness_LREC#2]
Thanks a lot for this dataset!

I have realized that your encoding considers subcategories of `normal` and `neither` as non-hate speech (at least for _English_). There are several label sub-categories so what exactly is `neither`? 

Also how about subcategory `link` and `spam`? They are considered hate speech currently according to your encoding. Your publication does not mention this either.

**Comment by xiaoleihuang** [comment]
@ogencoglu Hi, for the English, we resembled data from the three main publications, which do not explain the `link` as well. For the `spam`, please check this [paper](https://arxiv.org/pdf/1802.00393.pdf). `neither` and `normal` are defined as non-hateful content, according to those three datasets: [p1](https://www.aclweb.org/anthology/W16-5618.pdf); [p2](https://www.aclweb.org/anthology/N16-2013.pdf); [p3](https://arxiv.org/pdf/1802.00393.pdf).
We release the original raw labels to allow more exploration so that you can create your own encoder. Let me know if you have any more questions.

**Comment by ogencoglu** [comment]
Thank you for the swift reply!
